# Generated by Django 5.0.6 on 2024-06-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafe', '0002_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='mesa',
        ),
    ]
