# Generated by Django 5.0.6 on 2024-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafe', '0003_remove_cliente_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('isbn', models.IntegerField()),
                ('editorial', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='books')),
            ],
        ),
    ]
