# Generated by Django 5.0.6 on 2024-06-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCafe', '0004_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mesero',
        ),
    ]
